// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBTsncmvrZ8FuZidC_vHjHMpQ6b491_g8',
    appId: '1:732706020516:web:0494d60bb4dcb320acda31',
    messagingSenderId: '732706020516',
    projectId: 'litworm-7d207',
    authDomain: 'litworm-7d207.firebaseapp.com',
    databaseURL: 'https://litworm-7d207-default-rtdb.firebaseio.com',
    storageBucket: 'litworm-7d207.firebasestorage.app',
    measurementId: 'G-W991YB73DY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVlQ33BKrNqdeTmLi8hr0oi8sJwgTflbk',
    appId: '1:732706020516:android:b280db2d6f3a712dacda31',
    messagingSenderId: '732706020516',
    projectId: 'litworm-7d207',
    databaseURL: 'https://litworm-7d207-default-rtdb.firebaseio.com',
    storageBucket: 'litworm-7d207.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxPRtEllBbQlzkv1bweGHoH7-olP9P8jI',
    appId: '1:732706020516:ios:e8cee3232c05bfc9acda31',
    messagingSenderId: '732706020516',
    projectId: 'litworm-7d207',
    databaseURL: 'https://litworm-7d207-default-rtdb.firebaseio.com',
    storageBucket: 'litworm-7d207.firebasestorage.app',
    iosBundleId: 'com.example.litworm3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxPRtEllBbQlzkv1bweGHoH7-olP9P8jI',
    appId: '1:732706020516:ios:e8cee3232c05bfc9acda31',
    messagingSenderId: '732706020516',
    projectId: 'litworm-7d207',
    databaseURL: 'https://litworm-7d207-default-rtdb.firebaseio.com',
    storageBucket: 'litworm-7d207.firebasestorage.app',
    iosBundleId: 'com.example.litworm3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBTsncmvrZ8FuZidC_vHjHMpQ6b491_g8',
    appId: '1:732706020516:web:43720abdd03f3fe2acda31',
    messagingSenderId: '732706020516',
    projectId: 'litworm-7d207',
    authDomain: 'litworm-7d207.firebaseapp.com',
    databaseURL: 'https://litworm-7d207-default-rtdb.firebaseio.com',
    storageBucket: 'litworm-7d207.firebasestorage.app',
    measurementId: 'G-JS0WQMSSFG',
  );

}